services:
  db:
    image: postgres:16-alpine
    pull_policy: if_not_present
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: America/Guayaquil
      PGTZ: America/Guayaquil
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  lsg-msa-customer:
    build: ./lsg-msa-customer
    ports:
      - "8080:8080"
    environment:
      SECRET_CONFIG_DB_URL: ${CUSTOMER_DB_URL}
      SECRET_CONFIG_DB_USERNAME: ${DB_USERNAME}
      SECRET_CONFIG_DB_PASSWORD: ${DB_PASSWORD}
      CONFIG_HTTP_HTTPS_PORT: 8080
      ACCOUNT_API_BASE_URL: ${ACCOUNT_API_BASE_URL}
      ACCOUNT_API_EXISTS_ACTIVE_ACCOUNTS_PATH: ${ACCOUNT_API_EXISTS_ACTIVE_ACCOUNTS_PATH}
      TZ: America/Guayaquil
      JAVA_TOOL_OPTIONS: -Duser.timezone=America/Guayaquil
    depends_on:
      db:
        condition: service_healthy

  lsg-msa-account:
    build: ./lsg-msa-account
    ports:
      - "8081:8081"
    environment:
      SECRET_CONFIG_DB_URL: ${ACCOUNT_DB_URL}
      SECRET_CONFIG_DB_USERNAME: ${DB_USERNAME}
      SECRET_CONFIG_DB_PASSWORD: ${DB_PASSWORD}
      CONFIG_HTTP_HTTPS_PORT: 8081
      CUSTOMER_API_BASE_URL: ${CUSTOMER_API_BASE_URL}
      CUSTOMER_API_PATH: ${CUSTOMER_API_PATH}
      TZ: America/Guayaquil
      JAVA_TOOL_OPTIONS: -Duser.timezone=America/Guayaquil
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: